
name: Build
on:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.14.0' # The Go version to download (if necessary) and use.
    
    - name: Install Lint dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint

    - name: Install all dependencies
      run: |
        go get
        
    - name: Run build
      run: go build . 
      
    - name: Run vet & lint
      run: |
        go vet .
        golint .